[tool.poetry]
name = "filesystem-check"
version = "0.1.0"
description = ""
authors = ["Dominik Drexl <domdrexl@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
